import React, { useEffect, useRef, useState } from 'react';
import { AlertCircle, LogOut, Package } from 'lucide-react';
import { useAuth } from '../context/AuthContext.js';
import { Order } from '../types/index.js';
import { formatDate, formatNaira } from '../utils/formatters.js';

interface AccountPageProps { onSelectOrder: (order: Order) => void; onNavigateToShop: () => void; }

export const AccountPage: React.FC<AccountPageProps> = ({ onSelectOrder, onNavigateToShop }) => {
  const { user, token, isLoading, error, googleClientId, loginWithGoogleCredential, logout } = useAuth(); const [orders, setOrders] = useState<Order[]>([]); const [loadingOrders, setLoadingOrders] = useState(false); const googleButton = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!user && googleClientId && window.google?.accounts?.id && googleButton.current) { window.google.accounts.id.initialize({ client_id: googleClientId, callback: (response: { credential?: string }) => { if (response.credential) loginWithGoogleCredential(response.credential); } }); window.google.accounts.id.renderButton(googleButton.current, { theme: 'outline', size: 'large', text: 'signin_with', shape: 'rectangular', width: 280 }); } }, [user, googleClientId, loginWithGoogleCredential]);
  useEffect(() => { if (!user || !token) { setOrders([]); return; } setLoadingOrders(true); fetch('/api/orders/mine', { headers: { Authorization: `Bearer ${token}` } }).then((r) => r.json()).then(setOrders).catch(() => setOrders([])).finally(() => setLoadingOrders(false)); }, [user, token]);
  if (isLoading) return <div className="min-h-screen bg-[#fffaf2] py-24 text-center text-sm text-[#6f6a60]">Checking your account...</div>;
  if (!user) return <div className="min-h-screen bg-[#fffaf2] px-5 py-24 text-[#20251e] sm:px-8"><div className="mx-auto max-w-md border border-[#d9cdbb] bg-[#f0e7d8] p-8 text-center"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#a05b35]">Koko account</p><h1 className="mt-3 text-4xl font-black tracking-[-0.05em]">YOUR ORDERS, IN ONE PLACE.</h1><p className="mt-4 text-sm leading-6 text-[#6f6a60]">Sign in to see your pantry orders and delivery details.</p>{error && <div className="mt-5 flex gap-2 border border-[#d28b70] bg-[#f7e0d7] p-3 text-left text-xs text-[#8a3e26]"><AlertCircle className="h-4 w-4 shrink-0" />{error}</div>}{googleClientId && <div ref={googleButton} className="mt-5 flex justify-center" />} {!googleClientId && <p className="mt-5 text-xs text-[#6f6a60]">Google sign-in is not configured yet.</p>}</div></div>;
  return <div className="min-h-screen bg-[#fffaf2] px-5 py-12 text-[#20251e] sm:px-8 sm:py-20"><div className="mx-auto max-w-[1200px]"><div className="flex flex-col justify-between gap-5 border-b border-[#d9cdbb] pb-8 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#a05b35]">Koko account</p><h1 className="mt-3 text-5xl font-black tracking-[-0.06em]">HELLO, {user.name.split(' ')[0].toUpperCase()}.</h1><p className="mt-2 text-sm text-[#6f6a60]">{user.email}</p></div><button type="button" onClick={logout} className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-[#6f6a60] hover:text-[#a05b35]"><LogOut className="h-4 w-4" /> Sign out</button></div><section className="mt-12"><div className="flex items-center gap-3"><Package className="h-5 w-5 text-[#a05b35]" /><h2 className="text-2xl font-black">Order history</h2></div>{loadingOrders ? <p className="py-12 text-sm text-[#6f6a60]">Loading your orders...</p> : orders.length === 0 ? <div className="py-12"><p className="text-[#6f6a60]">No pantry orders yet.</p><button type="button" onClick={onNavigateToShop} className="mt-5 bg-[#20251e] px-5 py-3 text-xs font-bold uppercase tracking-[0.15em] text-white">Shop food</button></div> : <div className="mt-6 divide-y divide-[#d9cdbb] border-y border-[#d9cdbb]">{orders.map((order) => <button type="button" key={order.id} onClick={() => onSelectOrder(order)} className="flex w-full items-center justify-between gap-4 py-5 text-left hover:bg-[#f0e7d8]"><span><strong className="block">Order {order.order_number}</strong><span className="mt-1 block text-sm text-[#6f6a60]">{formatDate(order.created_at)} · {order.items.length} items</span></span><span className="font-bold">{formatNaira(order.total)}</span></button>)}</div>}</section></div></div>;
};
