import React, { useEffect, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowRight, Search, X } from 'lucide-react';
import { Product } from '../types/index.js';
import { formatNaira } from '../utils/formatters.js';

interface SearchModalProps { isOpen: boolean; onClose: () => void; onSelectProduct: (product: Product) => void; onSelectCategory: (category: string) => void; }

export const SearchModal: React.FC<SearchModalProps> = ({ isOpen, onClose, onSelectProduct, onSelectCategory }) => {
  const [term, setTerm] = useState(''); const [results, setResults] = useState<Product[]>([]); const [loading, setLoading] = useState(false); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { if (isOpen) window.setTimeout(() => input.current?.focus(), 40); else { setTerm(''); setResults([]); } }, [isOpen]);
  useEffect(() => { if (!term.trim()) { setResults([]); return; } const timer = window.setTimeout(() => { setLoading(true); fetch(`/api/products?search=${encodeURIComponent(term.trim())}`).then((r) => r.json()).then(setResults).catch(() => setResults([])).finally(() => setLoading(false)); }, 180); return () => window.clearTimeout(timer); }, [term]);
  return <AnimatePresence>{isOpen && <div className="fixed inset-0 z-50 flex items-start justify-center bg-[#20251e]/65 p-4 pt-16 sm:p-12"><motion.div initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} className="w-full max-w-2xl overflow-hidden bg-[#fffaf2]"><div className="flex items-center gap-3 border-b border-[#d9cdbb] bg-[#f0e7d8] p-4"><Search className="h-5 w-5 text-[#a05b35]" /><input ref={input} value={term} onChange={(e) => setTerm(e.target.value)} placeholder="Search pepper, rice, snacks..." className="flex-1 bg-transparent text-sm outline-none placeholder:text-[#9b9488]" /><button type="button" onClick={onClose} aria-label="Close search"><X className="h-5 w-5" /></button></div><div className="max-h-[65vh] overflow-y-auto p-5">{loading ? <p className="py-10 text-center text-sm text-[#6f6a60]">Looking through the pantry...</p> : results.length > 0 ? <div className="divide-y divide-[#d9cdbb]">{results.map((product) => <button type="button" key={product.id} onClick={() => { onSelectProduct(product); onClose(); }} className="flex w-full items-center gap-4 py-4 text-left hover:bg-[#f0e7d8]"><img src={product.image} alt={product.name} className="h-16 w-14 object-cover" /><span className="min-w-0 flex-1"><strong className="block truncate">{product.name}</strong><small className="mt-1 block uppercase tracking-[0.12em] text-[#a05b35]">{product.weight} · {product.category_slug}</small></span><span className="flex items-center gap-2 text-sm font-bold">{formatNaira(product.price)}<ArrowRight className="h-4 w-4" /></span></button>)}</div> : term ? <div className="py-10 text-center"><h3 className="text-2xl font-black">NOTHING ON THE SHELF</h3><p className="mt-2 text-sm text-[#6f6a60]">Try another product or category.</p></div> : <div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#a05b35]">Browse the pantry</p><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{['pantry', 'spices', 'snacks', 'breakfast', 'drinks'].map((category) => <button type="button" key={category} onClick={() => { onSelectCategory(category); onClose(); }} className="bg-[#f0e7d8] px-3 py-4 text-sm font-bold capitalize hover:bg-[#e2d5c2]">{category}</button>)}</div></div>}</div></motion.div></div>}</AnimatePresence>;
};
